#!/bin/env python

import argparse, random, pysam, re

def main(args):

    genome = None
    if args.fastaFile:
        genome = pysam.Fastafile(args.fastaFile)

    if args.requireseq and not args.fastaFile:
        raise ValueError("--requireseq set without -f/--fasta")

    maptabix = None
    if args.maptabix:
        maptabix = pysam.Tabixfile(args.maptabix, 'r')

    minlen = int(args.minlen)
    maxlen = int(args.maxlen)

    assert minlen <= maxlen

    chrlen = {}
    for line in open(args.indexFile, 'r'):
        c = line.strip().split()
        chr = c[0]
        size = int(c[1])
        chrlen[chr] = size

    # calculate offsets
    offset = 0
    chroffset = {}
    for chrom in sorted(chrlen.iterkeys()):
        offset += int(chrlen[chrom])
        chroffset[chrom] = offset

    genomelen = offset

    # random picks
    n = 0
    while n < int(args.numpicks):
        rndloc = random.randint(0,genomelen)
        lastoffset = 0
        rndchr = None
        for chrom in sorted(chrlen.iterkeys()):
            offset = int(chroffset[chrom])
            assert lastoffset < offset
            if rndloc >= lastoffset and rndloc < offset:
                rndchr = chrom
                rndloc -= lastoffset
            lastoffset = offset

        # handle single chromosome option
        if args.chrom and args.chrom != rndchr:
            continue

        fraglen = int(random.uniform(minlen,maxlen))

        fragstart = rndloc
        fragend   = rndloc + int(fraglen)

        # handle mappability option
        if maptabix:
            reject = False 

            if rndchr not in maptabix.contigs and 'chr' + rndchr in maptabix.contigs:
                mchrom = 'chr' + rndchr
            else:
                mchrom = rndchr 

            if mchrom in maptabix.contigs:
                for mapline in maptabix.fetch(mchrom, fragstart, fragend):
                    m = mapline.strip().split()
                    mscore = float(m[3])

                    if mscore < float(args.minmap):
                        reject = True
            if reject:
                continue

        # don't pick sites on contigs if --nocontigs is set
        if (rndchr.startswith('chr') and len(rndchr) > 5) or (not rndchr.startswith('chr') and len(rndchr) > 2):
            if args.nocontigs:
                continue

        if fragend < offset:
            if genome:
                seq = genome.fetch(rndchr,fragstart,fragend)
                assert seq

                if args.requireseq:
                    if re.search('[ATGCatgc]',seq):
                        print "\t".join((rndchr,str(fragstart),str(fragend),seq))
                        n += 1
                else:
                    print "\t".join((rndchr,str(fragstart),str(fragend),seq))
                    n += 1
            else:
                print "\t".join((rndchr,str(fragstart),str(fragend)))
                n += 1

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description="pick random sites from a samtools-indexed genome")
    parser.add_argument('-i', '--index', dest='indexFile', required=True, help="use the .fai file generated by samtools faidx yourgenome.fasta")
    parser.add_argument('-f', '--fasta', dest='fastaFile', default=None, help="if used, the fragment sequence is returned with coordinates")
    parser.add_argument('-n', '--num', dest='numpicks', required=True, help="number of sites to pick")
    parser.add_argument('-c', '--chr', dest='chrom', default=None, help='make mutations on one chromosome only')
    parser.add_argument('--maptabix', dest='maptabix', default=None, help='mappability tabix, required for --minmap')
    parser.add_argument('--minmap', dest='minmap', default=0.8, help='only select regions above mappability threshold (default 0.8)')
    parser.add_argument('--lmin', dest='minlen', default=1, help='minimum fragment length (default=1)')
    parser.add_argument('--lmax', dest='maxlen', default=1, help='maximum fragment length (default=1)')
    parser.add_argument('--requireseq', action="store_true", help="do not select hits in unsequenced regions, requires fasta file")
    parser.add_argument('--nocontigs', action="store_true", help="exclude contigs")
    args = parser.parse_args()
    main(args)
